spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: C44Hb7yAseY3oa
    url: jdbc:mariadb://localhost:3306/genshinbuildapp?createDatabaseIfNotExist=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always
    include-exception: true